// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Web platform Firebase configuration
  ///
  /// To configure Firebase for web:
  /// 1. Go to Firebase Console (https://console.firebase.google.com/)
  /// 2. Select your project
  /// 3. Click the Web icon (</>)
  /// 4. Register your app
  /// 5. Copy the configuration values below
  ///
  /// OR run: flutterfire configure
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE', // Replace with your API key
    appId: 'YOUR_APP_ID_HERE', // Replace with your App ID
    messagingSenderId: 'YOUR_SENDER_ID_HERE', // Replace with your Sender ID
    projectId: 'YOUR_PROJECT_ID_HERE', // Replace with your Project ID
    authDomain: 'YOUR_AUTH_DOMAIN_HERE', // e.g., your-project.firebaseapp.com
    storageBucket: 'YOUR_STORAGE_BUCKET_HERE', // e.g., your-project.appspot.com
    measurementId: 'YOUR_MEASUREMENT_ID_HERE', // Optional: for Analytics
  );

  /// Android platform Firebase configuration
  ///
  /// To configure Firebase for Android:
  /// 1. Download google-services.json from Firebase Console
  /// 2. Place it in android/app/
  /// 3. Run: flutterfire configure
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY', // Replace with Android API key
    appId: 'YOUR_ANDROID_APP_ID', // Replace with Android App ID
    messagingSenderId: 'YOUR_SENDER_ID', // Same as web
    projectId: 'YOUR_PROJECT_ID', // Same as web
    storageBucket: 'YOUR_STORAGE_BUCKET', // Same as web
  );

  /// iOS platform Firebase configuration
  ///
  /// To configure Firebase for iOS:
  /// 1. Download GoogleService-Info.plist from Firebase Console
  /// 2. Place it in ios/Runner/
  /// 3. Run: flutterfire configure
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // Replace with iOS API key
    appId: 'YOUR_IOS_APP_ID', // Replace with iOS App ID
    messagingSenderId: 'YOUR_SENDER_ID', // Same as web
    projectId: 'YOUR_PROJECT_ID', // Same as web
    storageBucket: 'YOUR_STORAGE_BUCKET', // Same as web
    iosBundleId: 'com.yourcompany.chatz', // Replace with your bundle ID
  );

  /// macOS platform Firebase configuration
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY', // Replace with macOS API key
    appId: 'YOUR_MACOS_APP_ID', // Replace with macOS App ID
    messagingSenderId: 'YOUR_SENDER_ID', // Same as web
    projectId: 'YOUR_PROJECT_ID', // Same as web
    storageBucket: 'YOUR_STORAGE_BUCKET', // Same as web
    iosBundleId: 'com.yourcompany.chatz', // Replace with your bundle ID
  );
}

/// IMPORTANT: This is a TEMPLATE file
///
/// Before running the app:
/// 1. Create a Firebase project at https://console.firebase.google.com/
/// 2. Register your app (Web, iOS, Android)
/// 3. Replace all "YOUR_*_HERE" placeholders with actual values
///
/// OR use FlutterFire CLI (recommended):
/// ```bash
/// dart pub global activate flutterfire_cli
/// flutterfire configure
/// ```
///
/// This will automatically generate this file with correct values
///
/// See docs/FIREBASE_SETUP.md for detailed instructions
